# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monkey < Formula
  desc "An interpreter for the Monkey programming language written in Go."
  homepage "https://github.com/alexruf/monkey"
  version "0.1.0-dev"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexruf/monkey/releases/download/v0.1.0-dev/monkey_0.1.0-dev_Darwin_x86_64.tar.gz"
      sha256 "487a8f2e4dfb595dfe3e932f999e4b5c6e0c74dba4af852fbf196ed899589b4d"
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexruf/monkey/releases/download/v0.1.0-dev/monkey_0.1.0-dev_Darwin_arm64.tar.gz"
      sha256 "17da68bcbafbe2313fdc320134e8836e4f518e8908b416d289ae0c451c64a085"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/alexruf/monkey/releases/download/v0.1.0-dev/monkey_0.1.0-dev_Linux_x86_64.tar.gz"
      sha256 "8b7287022ac22a38bf8da93da5dbee6e98d5dd01d9106cf4bf45194da32a6e25"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexruf/monkey/releases/download/v0.1.0-dev/monkey_0.1.0-dev_Linux_arm64.tar.gz"
      sha256 "18a300a7560241b08ce99fece2083110d10a7809ede1ef232bbd80e823ddafc7"
    end
  end

  depends_on "go" => :optional

  def install
    bin.install "monkey"
  end
end
